services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"

  dtupay-facade:
    image: dtupay-facade-service:latest
    container_name: rest-facade
    ports:
      - "8080:8080"