services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 15

  dtupay-facade:
    image: dtupay-facade-service:latest
    container_name: rest-facade
    ports:
      - "8080:8080"
    depends_on:
      rabbitMq:
        condition: service_healthy


  account-management:
    image: account-mgmt-service
    container_name: account-manager
    depends_on:
      rabbitMq:
        condition: service_healthy
